name: freshlens_ai_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  firebase_functions: ^0.0.1-dev

  # UI & Utility
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  flutter_slidable: ^3.1.0
  webview_flutter: ^4.7.0
  provider: ^6.1.2
  
  # AI & Machine Learning
  camera: ^0.11.0+1
  image_picker: ^1.1.2

  # Device & Services
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.3
  cloud_functions: ^5.6.2
  firebase_app_check: ^0.3.2+10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/