// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd4buEEQpwgCGd7tkLgcOWuhcq4GAcKFk',
    appId: '1:211287780020:android:b9b45bea72567f23f9c5e1',
    messagingSenderId: '211287780020',
    projectId: 'freshlens-1caf5',
    storageBucket: 'freshlens-1caf5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhE9JtCn6IYvVSsKxGJ2qo1WASaqW9o8',
    appId: '1:211287780020:web:5e1f46c230d20734f9c5e1',
    messagingSenderId: '211287780020',
    projectId: 'freshlens-1caf5',
    authDomain: 'freshlens-1caf5.firebaseapp.com',
    storageBucket: 'freshlens-1caf5.firebasestorage.app',
    measurementId: 'G-BR873XD0HF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqXyJ82eSxWH65w1nH3e6Cx3AeMWf1ug',
    appId: '1:211287780020:ios:9df4e25412a5e64bf9c5e1',
    messagingSenderId: '211287780020',
    projectId: 'freshlens-1caf5',
    storageBucket: 'freshlens-1caf5.firebasestorage.app',
    iosBundleId: 'com.example.freshlensAiApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqXyJ82eSxWH65w1nH3e6Cx3AeMWf1ug',
    appId: '1:211287780020:ios:9df4e25412a5e64bf9c5e1',
    messagingSenderId: '211287780020',
    projectId: 'freshlens-1caf5',
    storageBucket: 'freshlens-1caf5.firebasestorage.app',
    iosBundleId: 'com.example.freshlensAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxhE9JtCn6IYvVSsKxGJ2qo1WASaqW9o8',
    appId: '1:211287780020:web:a943d4229c3394baf9c5e1',
    messagingSenderId: '211287780020',
    projectId: 'freshlens-1caf5',
    authDomain: 'freshlens-1caf5.firebaseapp.com',
    storageBucket: 'freshlens-1caf5.firebasestorage.app',
    measurementId: 'G-QY2H4B0CEF',
  );

}